In [24]:
import pandas as pd 
import numpy as np 
from sklearn import feature_extraction, linear_model, model_selection, preprocessing
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression

In [2]:
# 读取数据
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [29]:
# 将文字转换成稀疏矩阵
TfidfVectorizer = feature_extraction.text.TfidfVectorizer()
train_vectors = TfidfVectorizer.fit_transform(train["text"])
test_vectors = TfidfVectorizer.transform(test["text"])

In [46]:
# linear classifier
clf = linear_model.RidgeClassifier()
scores = model_selection.cross_val_score(clf, train_vectors, train["target"], cv=3, scoring="f1")
scores

array([0.63366337, 0.6122449 , 0.68442211])

In [47]:
# Logistic regression
clf = LogisticRegression()
clf.fit(train_vectors, train['target'])
scores = model_selection.cross_val_score(clf, train_vectors, train["target"], cv=3, scoring="f1")
scores

array([0.62111801, 0.59760087, 0.68120457])

In [43]:
# Gradient boost decision tree
clf = GradientBoostingClassifier()
scores = model_selection.cross_val_score(clf, train_vectors, train["target"], cv=3, scoring="accuracy")
scores

array([0.69385343, 0.66390859, 0.69452109])

In [5]:
# submission 
clf.fit(train_vectors, train["target"])
sample_submission = pd.read_csv("sample_submission.csv")
sample_submission["target"] = clf.predict(test_vectors)
# sample_submission.to_csv("submission.csv", index=False)